/* confdefs.h */
#define PACKAGE_NAME "geda-ai"
#define PACKAGE_TARNAME "geda-ai"
#define PACKAGE_VERSION "1.0.0"
#define PACKAGE_STRING "geda-ai 1.0.0"
#define PACKAGE_BUGREPORT "https://github.com/tambotitree/geda-ai/issues"
#define PACKAGE_URL ""
#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STRINGS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define HAVE_WCHAR_H 1
#define HAVE_SYS_PARAM_H 1
#define STDC_HEADERS 1
#define _ALL_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define __EXTENSIONS__ 1
#define PACKAGE "geda-ai"
#define VERSION "1.0.0"
#define PACKAGE_DATE_VERSION "1.0.0"
#define YYTEXT_POINTER 1
#define OS_CARBON 1
#define SHOW_URI_COMMAND "open"
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
